### ISSUE TITLE
`ReferenceError: __dirname is not defined` when using sub-directory for root

### ISSUE THREAD

**Issue by droegier** [vercel/ai-chatbot#219]
If I take the boilerplate codebase here, put it in a subdirectory, and set all ENV variables, it runs without issues locally.

When I release to Vercel, with the ENV vars and I note the subdirectory in the root folder setting, I get the following error:, when calling the frontend on the browser.

```
ReferenceError: __dirname is not defined
    at (frontend/node_modules/.pnpm/next@14.0.4-canary.17_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/ua-parser-js/ua-parser.js:1:17315)
    at (frontend/node_modules/.pnpm/next@14.0.4-canary.17_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/ua-parser-js/ua-parser.js:1:17444)
    at (frontend/node_modules/.pnpm/next@14.0.4-canary.17_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/web/spec-extension/user-agent.js:27:59)
    at (frontend/node_modules/.pnpm/next@14.0.4-canary.17_react-dom@18.2.0_react@18.2.0/node_modules/next/server.js:8:0)
    at (frontend/node_modules/.pnpm/next-auth@5.0.0-beta.3_next@14.0.4-canary.17_react@18.2.0/node_modules/next-auth/lib/index.js:3:24)
    at (frontend/node_modules/.pnpm/next-auth@5.0.0-beta.3_next@14.0.4-canary.17_react@18.2.0/node_modules/next-auth/index.js:52:0)
 ```
 
<img width="1269" alt="image" src="https://github.com/vercel/ai-chatbot/assets/16133184/6984cb07-c4a4-42bb-922a-eb320b96f967">

**Comment by droegier** [comment]
Fixed it, config issue, regarding framework selection in Vercel

**Comment by adisharma29** [comment]
How did you fix this?
