### ISSUE TITLE
onFinish strange error with Drizzle/BASE_URL: "values() must be called with at least one value"

### ISSUE THREAD

**Issue by fullstackwebdev** [vercel/ai-chatbot#619]
Using the repo's onFinished I am getting an error, but only when tool calling. Is there a way to get better tracing or debugging for resolving this?  All this abstraction seems to be confusing, what is the actual error?

```
 GET /api/files/df381887-0a81-461b-8179-ac9de943c373.jpeg 200 in 195ms
 GET /api/history 200 in 364ms
Failed to save messages in database Error: values() must be called with at least one value
    at PgInsertBuilder.values (turbopack://[project]/node_modules/.pnpm/drizzle-orm@0.34.1_@neondatabase+serverless@0.9.5_@opentelemetry+api@1.9.0_@types+pg@8.11.6_@_bxbm5u47tukj6nmhfvnnj7uaym/node_modules/src/pg-core/query-builders/insert.ts:54:9)
    at saveMessages (turbopack://[project]/lib/db/queries.ts:111:36)
    at onFinish (turbopack://[project]/app/(chat)/api/chat/route.ts:342:29)
    at Object.flush (turbopack://[project]/node_modules/.pnpm/ai@4.0.10_react@19.0.0-rc-45804af1-20241021_zod@3.23.8/node_modules/ai/core/generate-text/stream-text.ts:920:26)
  52 | 		values = Array.isArray(values) ? values : [values];
  53 | 		if (values.length === 0) {
> 54 | 			throw new Error('values() must be called with at least one value');
     | 			     ^
  55 | 		}
  56 | 		const mappedValues = values.map((entry) => {
  57 | 			const result: Record<string, Param | SQL> = {};
Failed to save chat
 POST /api/chat 200 in 1237ms
 GET /api/history 200 in 300ms
 GET /api/vote?chatId=20a2e516-9c8f-40eb-86ab-7f48a7beddd1 200 in 314ms



```

**Comment by sailxjx** [comment]
I have the same problem.

**Comment by wjx** [comment]
If you add new tool calls, ensure that you include them in both the AllowedTools type and the allTools array in /api/chat/route.ts. Failing to do so will result in incomplete messages being passed to onFinish when the tool is invoked, causing the aforementioned error.

**Comment by sailxjx** [comment]
> If you add new tool calls, ensure that you include them in both the AllowedTools type and the allTools array in /api/chat/route.ts. Failing to do so will result in incomplete messages being passed to onFinish when the tool is invoked, causing the aforementioned error.

That's the correct answer, the document missing this step.

**Comment by fullstackwebdev** [comment]
Hi thanks, I also get it on image uploading.

**Comment by wjx** [comment]
> Hi thanks, I also get it on image uploading.

How do you upload image?
